; PlatformIO Project Configuration File for ENCO-02 Robot
; Main Controller: ESP32 IoT Board + 2.0" ST7789 Color LCD

[platformio]
src_dir = src

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = arduino
upload_speed = 921600
monitor_speed = 115200
custom_component_remove =
  espressif/esp_hosted
  espressif/esp_wifi_remote
  espressif/esp-dsp
  espressif/esp32-camera
  espressif/libsodium
  espressif/esp-modbus
  espressif/qrcode
  espressif/esp_insights
  espressif/esp_diag_data_store
  espressif/esp_diagnostics
  espressif/esp_rainmaker
  espressif/rmaker_common
build_flags =
  -fno-exceptions
  -Wall
  -Werror
  -Wno-error=unused-variable
  -llibopus
  -llibesp_audio_codec
  -llibesp_audio_simple_dec
  -Os

build_src_filter =
  +<**/*.c>
  +<**/*.cpp>
  -<**/*.S>
  -<**/*.asm>

[env:enco02_main]
board = esp32dev
board_build.mcu = esp32
build_src_filter =
  ${env.build_src_filter}
  +<../firmware/main/*.c*>
build_flags =
  ${env.build_flags}
  -Lsrc/${this.board_build.mcu}
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -I firmware/main/
lib_deps = lvgl/lvgl@9.2.2
board_build.partitions = firmware/main/partitions_4M.csv
