include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/l10n/app_localizations*.dart
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
