// Generated by tools/face_assets/build_face_assets.py - do not edit by hand.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Which characters are compiled in. Each one costs roughly 0.3-0.4 MB of flash; override with
// -D ENCO_CHAR_<ID>=0 to leave one out (its art and face_assets_<id>.c stay in the tree).
#ifndef ENCO_CHAR_K3
#define ENCO_CHAR_K3 1
#endif
#ifndef ENCO_CHAR_FOX
#define ENCO_CHAR_FOX 1
#endif

#define ENCO_FACE_W 240
#define ENCO_FACE_H 320

// Pre-scaled bust for the camera HUD's side panel, baked at build time.
#define ENCO_FACE_THUMB_W 82
#define ENCO_FACE_THUMB_H 86

// A named facial expression: an eyes sprite and a mouth sprite. Eye sprites sit at the
// character's eyes_x/eyes_y, mouth sprites at mouth_x/mouth_y.
typedef struct {
  const char* name;
  const lv_image_dsc_t* eyes;
  const lv_image_dsc_t* mouth;
} enco_face_expr_t;

// Wind-in-the-hair geometry. Row r covers portrait row y0 + r. spans[r * 10 ..] holds, in portrait
// x, the left side then the right side as (p0, p1, p2, body0, body1): the sideways sway is zero at
// p0 and p2 (backdrop / face, neck, dress), strongest at p1 (the outer strands), linear in between,
// and fades to zero over `feather` px towards [body0, body1] - a bare shoulder that must stay put
// (none when body0 > body1). amp[r] / amp_unit is the row's sway amplitude in px.
typedef struct {
  int16_t y0;
  uint16_t rows;
  uint8_t amp_unit;
  uint8_t feather;
  const uint8_t* amp;
  const int16_t* spans;
} enco_hair_flow_t;

// An ornament riding on an ear (a flower, an earring, a bead string). It is carried along with the
// ear's root but turns about `x, y` by an angle of its own: a damped spring that pulls it towards
// the ear's angle, or - by `hang` / 255 - towards hanging plumb. hz10 / 10 is the swing frequency,
// zeta100 / 100 the damping ratio.
typedef struct {
  int16_t x, y;
  uint8_t hang;
  uint8_t hz10;
  uint8_t zeta100;
} enco_ear_deco_t;

// One ear: a bone turning about its root (pivot) towards its tip. weight[] (box_w x box_h, from
// box_x, box_y) is how much each pixel follows the ear, 0..255; deco_map[] is (ornament << 6) |
// how much it follows that ornament instead, 0..63. out_sign turns "outward" (positive) into a
// screen rotation: -1 for her left-on-screen ear (tip goes left), +1 for the other.
typedef struct {
  int16_t box_x, box_y;
  uint8_t box_w, box_h;
  int16_t pivot_x, pivot_y;
  int16_t tip_x, tip_y;
  int8_t out_sign;
  uint8_t deco_count;
  enco_ear_deco_t deco[4];
  const uint8_t* weight;
  const uint8_t* deco_map;
} enco_ear_t;

// Everything display.cpp needs to draw and animate one character.
typedef struct {
  const char* id;
  const lv_image_dsc_t* base;   // full-screen ENCO_FACE_W x ENCO_FACE_H portrait
  const lv_image_dsc_t* thumb;  // ENCO_FACE_THUMB_W x ENCO_FACE_THUMB_H camera-HUD bust
  uint32_t bg_color;            // face container fill, matching the portrait's backdrop

  // Blink, lip-sync and expression sprites (all opaque, positioned at the offsets below).
  int16_t eyes_x, eyes_y;
  int16_t mouth_x, mouth_y;
  const lv_image_dsc_t* eyes_half;
  const lv_image_dsc_t* eyes_shut;
  const lv_image_dsc_t* mouth_small;
  const lv_image_dsc_t* mouth_wide;
  const enco_face_expr_t* exprs;
  uint8_t expr_count;

  // Hair breeze. Each table holds 5 frames indexed by level + 2 (level -2 full-left .. +2
  // full-right); [2] is NULL because the base portrait already shows the hair at rest. NULL tables
  // mean the character has no breeze.
  int16_t bangs_x, bangs_y;
  int16_t locks_l_x, locks_l_y;
  int16_t locks_r_x, locks_r_y;
  const lv_image_dsc_t* const* bangs;
  const lv_image_dsc_t* const* locks_l;
  const lv_image_dsc_t* const* locks_r;

  // Falling petals: petal_sizes x petal_frames RGB565A8 sprites, size-major, one tumble cycle per
  // size. They fall left of petal_lane_l and right of petal_lane_r, clear of her face. NULL: none.
  const lv_image_dsc_t* const* petals;
  uint8_t petal_frames;
  uint8_t petal_sizes;
  int16_t petal_lane_l, petal_lane_r;

  // Wind in the long hair, warped at runtime (display.cpp WarpHairChunk). NULL: no flow.
  const enco_hair_flow_t* hair_flow;

  // Twitching ears, warped at runtime (display.cpp WarpEarsChunk). NULL / 0: none.
  const enco_ear_t* ears;
  uint8_t ear_count;
} enco_character_t;

#if ENCO_CHAR_K3
extern const enco_character_t enco_char_k3;  // K3 Elegant Bob (silver hair, white armour)
#endif
#if ENCO_CHAR_FOX
extern const enco_character_t enco_char_fox;  // Fox (pink fox-girl, crimson dress)
#endif

#ifdef __cplusplus
}
#endif
