// Generated by tools/face_assets/build_face_assets.py - do not edit by hand.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ENCO_FACE_W 240
#define ENCO_FACE_H 320

// Overlay sprites are positioned at these offsets inside the base image.
#define ENCO_FACE_EYES_X 64
#define ENCO_FACE_EYES_Y 102
#define ENCO_FACE_MOUTH_X 96
#define ENCO_FACE_MOUTH_Y 162

extern const lv_image_dsc_t enco_face_base;
extern const lv_image_dsc_t enco_face_eyes_half;
extern const lv_image_dsc_t enco_face_eyes_shut;
extern const lv_image_dsc_t enco_face_mouth_small;
extern const lv_image_dsc_t enco_face_mouth_wide;

#ifdef __cplusplus
}
#endif
