"""Sci-fi mecha accessories, lifted straight out of the approved concept render.

Where the artwork comes from
----------------------------
source/concept_a_accessories.jpg is the Concept A mock-up, generated by the image model from
build/frame_base.png with a prompt asking for a 发卡 on the left temple and a thin temple device
on the right. It is the art that was signed off, so it is the art that ships - an earlier
version of this file reconstructed the same shapes as hand-written polygons and simply was not
as good: no amount of tuning reproduces the generator's shading on a 14x30px plate.

The catch is that the generator does not *add* to its reference, it repaints it. Measured
against the clean portrait it changed 21.6% of all pixels - it redrew her bodysuit almost
entirely and nudged her whole silhouette by about a pixel. So the render cannot be used as a
source portrait; only the accessory pixels can be taken from it, and they have to be cut out.

How the cut-out works
---------------------
1. Diff the render against the clean portrait, restricted to two generous windows around the
   accessories. Everything the generator changed elsewhere is thereby ignored.
2. Erode. Inside those windows the only other thing that moved is the one-pixel silhouette
   shift along her hair edge, and a one-pixel line has at most two set neighbours, so requiring
   five kills it while barely touching a solid plate.
3. Keep the largest blob per window, discarding whatever speckle survived.
4. Dilate back out and re-intersect with the raw diff, which recovers the accessory's own soft
   edge without letting the thin lines return.

Why this is code and not five edited JPEGs
------------------------------------------
The blink, mouth and hair-sway sprites are crops taken from *different* source images. Anything
present in one but not the others flickers as she animates - blink once and the hair clip would
vanish for two frames. Applying one cut-out to every frame makes that impossible by
construction: the same pixels are painted into all nine, so the change-mask between base and
variant sees nothing there and the sprite rectangles do not move.

Two ordering constraints, both of which bite if you get them wrong:

* **Composite after warp_hair(), never before.** The warp slides pixels sideways by up to 3px,
  which turns hard-edged metal into a smear.
* **Compute the palette before compositing, from the clean portrait.** median_cut() splits the
  largest box in RGB space, and the emitter cyan sits a long way from everything else in this
  picture, so if it can see the accessories it hands cyan several of the sixteen slots and
  starves the face. Build the palette from the accessory-free portrait at 15 colours and pin
  the accent on the end.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "source")

W, H = 240, 320

# Generous boxes around each accessory, in the portrait's own 240x320 space. They only have to
# exclude the rest of the character; the diff finds the actual shape.
WINDOWS = [
    (24, 44, 82, 112),  # 发卡, left temple
    (168, 92, 216, 132),  # temple device, right
]

# Sum-of-channels difference. Comfortably above JPEG ringing, comfortably below a real repaint.
THRESHOLD = 60

# Sanity bounds on the cut-out. If the render is ever replaced and the extraction goes wrong,
# the build should stop rather than quietly ship a smear of her hair.
EXPECT_BLOBS = 2
MIN_PIXELS, MAX_PIXELS = 900, 2600

_overlay = None  # {pixel index: (r, g, b)}, computed once


def _erode(mask, w, h, need=5):
    """Drop pixels with fewer than `need` of their 8 neighbours set."""
    out = bytearray(w * h)
    for i in range(w * h):
        if not mask[i]:
            continue
        x, y = i % w, i // w
        n = 0
        for dy in (-1, 0, 1):
            for dx in (-1, 0, 1):
                if dx or dy:
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < w and 0 <= ny < h and mask[ny * w + nx]:
                        n += 1
        if n >= need:
            out[i] = 1
    return out


def _build_overlay():
    # Imported here rather than at module scope: face_lib imports cleanly either way, but this
    # keeps the module importable for the geometry checks without shelling out to sips.
    import face_lib as F

    clean, w, h = F.load_rgb(os.path.join(SOURCE, "portrait_base.jpg"), W, H)
    render, _, _ = F.load_rgb(os.path.join(SOURCE, "concept_a_accessories.jpg"), W, H)

    raw = bytearray(w * h)
    for x0, y0, x1, y1 in WINDOWS:
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                i = y * w + x
                a, b = clean[i], render[i]
                if abs(a[0] - b[0]) + abs(a[1] - b[1]) + abs(a[2] - b[2]) > THRESHOLD:
                    raw[i] = 1

    core, kept = F.keep_main_blobs(_erode(raw, w, h), w, h)
    mask = bytearray(g and r for g, r in zip(F.dilate(core, w, h, 2), raw))

    n = sum(mask)
    assert len(kept) == EXPECT_BLOBS, f"expected {EXPECT_BLOBS} accessory blobs, got {kept}"
    assert MIN_PIXELS <= n <= MAX_PIXELS, f"accessory cut-out is {n}px, expected {MIN_PIXELS}..{MAX_PIXELS}"
    return {i: render[i] for i in range(w * h) if mask[i]}


def overlay():
    global _overlay
    if _overlay is None:
        _overlay = _build_overlay()
    return _overlay


def accent_colors():
    """The palette slots to reserve: the single most saturated colour in the cut-out.

    Derived from the artwork rather than hard-coded, so swapping in a differently-lit concept
    render does not silently leave the emitter quantising onto a grey.
    """
    best, best_sat = None, -1
    for rgb in overlay().values():
        sat = max(rgb) - min(rgb)
        if sat > best_sat:
            best, best_sat = rgb, sat
    return [best]


def draw(rgb, w, h):
    """Composite the accessories onto a flat list of (r, g, b). Mutates and returns it."""
    assert (w, h) == (W, H), f"overlay is fixed at {W}x{H}, got {w}x{h}"
    for i, colour in overlay().items():
        rgb[i] = colour
    return rgb
