#!/usr/bin/env python3
"""Regenerate firmware/main/face_assets.{c,h} from the source portraits.

    python3 tools/face_assets/build_face_assets.py firmware/main

Emits one full-screen 240x320 I4 base image plus small I4 overlay sprites for the blink and mouth
frames.  Every image shares the base's 16-colour palette, which is what lets the overlays composite
onto the base without a seam.

The overlay rectangles are not hand-tuned: each variant is compared against the base and the
rectangle is the bounding box of the pixels that actually changed, so they are exactly as large as
they need to be and no larger.  That matters because a smaller sprite means a smaller region of the
screen is invalidated when it is swapped, which is the whole reason the animation is cheap.

Intermediate artefacts (the quantised palette + index map, and composite previews) land in
tools/face_assets/build/ for align_check.py and zoom_face.py to use.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import face_lib as F

SOURCE = os.path.join(HERE, "source")
BUILD = os.path.join(HERE, "build")

W, H = 240, 320

# source file, window to search for changes in (x, y, w, h), sprite group, C symbol
VARIANTS = [
    ("portrait_eyes_half.jpg",   (40, 100, 160, 60), "eyes",  "enco_face_eyes_half"),
    ("portrait_eyes_shut.jpg",   (40, 100, 160, 60), "eyes",  "enco_face_eyes_shut"),
    ("portrait_mouth_small.jpg", (70, 145, 100, 60), "mouth", "enco_face_mouth_small"),
    ("portrait_mouth_wide.jpg",  (70, 145, 100, 60), "mouth", "enco_face_mouth_wide"),
]

# Re-quantising a JPEG variant flips a sprinkle of isolated pixels all over the image, so a plain
# bounding box of "anything that differs" covers the whole search window.  Keep only differing
# pixels that sit in a solidly-changed neighbourhood (a 3x3 erosion): real edits are contiguous
# blobs, compression noise is not.
NEIGHBOURS = 6  # of the 9 pixels in the 3x3 block
PAD = 3


def diff_box(base, var, w, win):
    wx, wy, ww, wh = win
    d = [[1 if base[y * w + x] != var[y * w + x] else 0 for x in range(wx, wx + ww)]
         for y in range(wy, wy + wh)]
    xs, ys = [], []
    for y in range(1, wh - 1):
        for x in range(1, ww - 1):
            if not d[y][x]:
                continue
            if sum(d[y + dy][x + dx] for dy in (-1, 0, 1) for dx in (-1, 0, 1)) >= NEIGHBOURS:
                xs.append(wx + x)
                ys.append(wy + y)
    if not xs:
        return None
    return min(xs), min(ys), max(xs), max(ys)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    outdir = sys.argv[1]
    os.makedirs(outdir, exist_ok=True)
    os.makedirs(BUILD, exist_ok=True)

    pixels, w, h = F.load_rgb(os.path.join(SOURCE, "portrait_base.jpg"), W, H)
    # Sampling every 4th pixel is plenty for flat cel-shaded art and keeps this to about a second.
    palette = F.median_cut(pixels[::4], F.N_COLORS)
    base = F.build_index_map(pixels, palette)
    F.save_state(os.path.join(BUILD, "state.bin"), palette, base, w, h)

    quantised, boxes = {}, {}
    for fname, win, group, name in VARIANTS:
        pixels, _, _ = F.load_rgb(os.path.join(SOURCE, fname), w, h)
        var = F.build_index_map(pixels, palette)
        quantised[name] = var
        box = diff_box(base, var, w, win)
        assert box, f"{fname}: no change detected in {win}"
        print(f"{name}: change box {box}")
        prev = boxes.get(group)
        boxes[group] = box if prev is None else (min(prev[0], box[0]), min(prev[1], box[1]),
                                                 max(prev[2], box[2]), max(prev[3], box[3]))

    # Pad, clamp, and snap x/width to even numbers so every I4 row starts on a byte boundary.
    rects = {}
    for group, (x1, y1, x2, y2) in boxes.items():
        x1 = max(0, x1 - PAD) & ~1
        y1 = max(0, y1 - PAD)
        x2 = min(w - 1, x2 + PAD)
        y2 = min(h - 1, y2 + PAD)
        rects[group] = (x1, y1, ((x2 - x1 + 1) + 1) & ~1, y2 - y1 + 1)
        print(f"{group} sprite: x={rects[group][0]} y={rects[group][1]} "
              f"{rects[group][2]}x{rects[group][3]}")

    total = 0
    with open(os.path.join(outdir, "face_assets.c"), "w") as fh:
        fh.write("// Generated by tools/face_assets/build_face_assets.py - do not edit by hand.\n"
                 "//\n"
                 "// A full-screen 16-colour base portrait plus small overlay sprites for the blink and\n"
                 "// mouth frames.  I4 keeps the whole set under 50KB of flash; see lv_i4_decoder.c for\n"
                 "// why a custom LVGL decoder is needed to draw it without a framebuffer.\n"
                 "\n#include \"face_assets.h\"\n")
        total += F.emit_c(fh, "enco_face_base", base, palette, w, h)
        for fname, win, group, name in VARIANTS:
            x, y, cw, ch = rects[group]
            total += F.emit_c(fh, name, F.crop(quantised[name], w, h, x, y, cw, ch), palette, cw, ch)

    with open(os.path.join(outdir, "face_assets.h"), "w") as fh:
        ex, ey, _, _ = rects["eyes"]
        mx, my, _, _ = rects["mouth"]
        fh.write("// Generated by tools/face_assets/build_face_assets.py - do not edit by hand.\n"
                 "#pragma once\n\n#include \"lvgl.h\"\n\n"
                 "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
                 f"#define ENCO_FACE_W {w}\n#define ENCO_FACE_H {h}\n\n"
                 "// Overlay sprites are positioned at these offsets inside the base image.\n"
                 f"#define ENCO_FACE_EYES_X {ex}\n#define ENCO_FACE_EYES_Y {ey}\n"
                 f"#define ENCO_FACE_MOUTH_X {mx}\n#define ENCO_FACE_MOUTH_Y {my}\n\n"
                 "extern const lv_image_dsc_t enco_face_base;\n"
                 "extern const lv_image_dsc_t enco_face_eyes_half;\n"
                 "extern const lv_image_dsc_t enco_face_eyes_shut;\n"
                 "extern const lv_image_dsc_t enco_face_mouth_small;\n"
                 "extern const lv_image_dsc_t enco_face_mouth_wide;\n\n"
                 "#ifdef __cplusplus\n}\n#endif\n")

    # Composite previews, so each frame can be eyeballed exactly as the device will draw it.
    F.write_png_indexed(os.path.join(BUILD, "frame_base.png"), base, palette, w, h)
    for fname, win, group, name in VARIANTS:
        x, y, cw, ch = rects[group]
        comp = list(base)
        for yy in range(ch):
            for xx in range(cw):
                comp[(y + yy) * w + (x + xx)] = quantised[name][(y + yy) * w + (x + xx)]
        F.write_png_indexed(os.path.join(BUILD, f"frame_{name}.png"), comp, palette, w, h)

    print(f"\nwrote {outdir}/face_assets.c + .h, {total:,} bytes of flash")
    print(f"previews in {BUILD}")


if __name__ == "__main__":
    main()
