"""Gzip firmware/main/web/servo_index.html into a C header for the debug web server.

Runs as a PlatformIO pre-build script (extra_scripts = pre:tools/gen_web_page.py) and can also be
run by hand: python3 tools/gen_web_page.py

The page is served with "Content-Encoding: gzip". Raw it is ~13 KB, which needs more TCP send
buffers than the heap has while a voice session is live; gzipped it is ~3.5 KB.
"""

import gzip
import os

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(ROOT, "firmware", "main", "web", "servo_index.html")
DST = os.path.join(ROOT, "firmware", "main", "servo_index_html.h")


def generate():
    if os.path.exists(DST) and os.path.getmtime(DST) >= os.path.getmtime(SRC):
        return
    with open(SRC, "rb") as f:
        raw = f.read()
    # mtime=0 keeps the output byte-identical across builds.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(packed), 16):
        lines.append("  " + ", ".join("0x%02x" % b for b in packed[i:i + 16]) + ",")
    with open(DST, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_web_page.py from web/servo_index.html - do not edit.\n")
        f.write("#pragma once\n#include <stdint.h>\n#include <pgmspace.h>\n\n")
        f.write("// %d bytes raw, %d bytes gzipped.\n" % (len(raw), len(packed)))
        f.write("static const uint8_t kServoIndexHtmlGz[] PROGMEM = {\n")
        f.write("\n".join(lines))
        f.write("\n};\n")
    print("gen_web_page: %s (%d -> %d bytes)" % (os.path.relpath(DST, ROOT), len(raw), len(packed)))


generate()
